config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
# frozen_string_literal: true

class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attrs) { attrs['name'].blank? }
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(width: '600', height: '400')
    self.thumb_image ||= Placeholder.image_generator(width: '350', height: '200')
  end
end

app/controllers/portfolios_controller.rb
# frozen_string_literal: true

class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy]
  layout 'portfolio'
  access all: %i[show index angular],
         user: { except: %i[destroy new create update edit sort] },
         site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    head :ok
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def show; end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html do
          redirect_to portfolios_url,
                      notice: 'Your portflio is now live'
        end
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_item_params)
        format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was removed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def portfolio_item_params
    params.require(:portfolio).permit(:title,
                                      :body,
                                      :subtitle,
                                      technologies_attributes: [:name])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: "form-control" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, rows: 13, class: "form-control" %>
    </div>
  </div>
  <div class="col-md-12">
    <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |techology_form| %>
      <div class="form-group">
        <%= techology_form.label :name %>
        <%= techology_form.text_field :name, class: "form-control"%>
      </div>
      <% end %>
    </div>
    <div class="button-group">
      <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block'%>
    </div>
  </div>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
    <div class="card-header">
      <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %>
    </div>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
    <div class="card-body">
      <h5 class="card-title">
        <%# <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %>
        <span class="badge badge-secondary"><%= portfolio_item.subtitle %></span>
      </h5>
      <p class="card-text">
        <%# <%= portfolio_item.body %> 
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", portfolio_show_path(portfolio_item.id), class: "btn btn-sm btn-outline-primary" %>
          <% if logged_in?(:site_admin) %>
          <%= link_to "Edit", edit_portfolio_path(portfolio_item.id), class: "btn btn-sm btn-outline-secondary" %>
          <%# <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), 
                method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin), 
                class: "btn btn-sm btn-outline-danger" %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
  <td><%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag @portfolio_item.main_image, class: 'img-fluid' %>
        </div>
        <div class="col-md-5">
            <h1>
                <%= @portfolio_item.title %>
            </h1>

            <hr />

            <em>
                <%= @portfolio_item.subtitle %></em>

            <p>
                <%= @portfolio_item.body %>
            </p>

            <h3>Technologies Used:</h3>
            <% @portfolio_item.technologies.each do |technology| %>
            <p>
                <%= technology.name %>
            </p>
            <% end %>
        </div>
    </div>
</div>